version: '3.8'

services:
  sse-server-native:
    build:
      context: .
      dockerfile: Dockerfile.native
    container_name: sse-jetty-server-native
    ports:
      - "8080:8080"
    volumes:
      - ./www:/var/www/public
    environment:
      # Cloud Run compatible environment
      PORT: 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Resource limits for native image
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  redis-data:
