version: '3.8'

services:
  sse-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sse-jetty-server
    ports:
      - "8080:8080"
    volumes:
      - ./www:/var/www/public
    # depends_on:
    #   - redis
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"

  # redis:
  #   image: redis:latest
  #   container_name: sse-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  redis-data: